'use strict';
/* Existing static RTL interface, new stateless Supabase Auth + RLS backend. */
const express=require('express');
const path=require('node:path');
const crypto=require('node:crypto');
const V=require('./lib/validation');
const app=express();app.disable('x-powered-by');
const ROOT=__dirname,SB=String(process.env.SUPABASE_URL||'').replace(/\/$/,''),KEY=process.env.SUPABASE_ANON_KEY||'',SECRET=process.env.SUPABASE_SERVICE_ROLE_KEY||'',ORIGIN=process.env.SITE_URL||'',BUCKET='marketplace-media';
const fail=(s,m)=>{throw Object.assign(new Error(m),{status:s});};
async function upstream(url,{method='GET',body,token=KEY,secret=false,headers={}}={}){
 const k=secret?SECRET:KEY;if(!SB||!k)fail(503,'configuration_required');
 const r=await fetch(SB+url,{method,headers:{apikey:k,Authorization:`Bearer ${secret?SECRET:token}`,...(body instanceof Buffer?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:body instanceof Buffer?body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
 const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null;}catch{data=null;}
 if(!r.ok)fail(r.status>=500?503:r.status,'upstream_request_failed');return {data,headers:r.headers};
}
async function db(table,query='',opt={}){return (await upstream('/rest/v1/'+table+query,opt)).data;}
const rpc=(name,body,token,secret=false)=>db('rpc/'+name,'',{method:'POST',body,token,secret});
function cookies(req){const r={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0){try{r[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1));}catch{}}}return r;}
function cookie(res,name,val,age){res.append('Set-Cookie',`${name}=${encodeURIComponent(val)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${process.env.NODE_ENV==='production'?'; Secure':''}`);}
function setSession(res,s){cookie(res,'sq_access',s.access_token,Math.max(60,s.expires_in||3600));cookie(res,'sq_refresh',s.refresh_token,604800);}
function clear(res){cookie(res,'sq_access','',0);cookie(res,'sq_refresh','',0);}
async function auth(req,res,next){try{
 const c=cookies(req);let token=c.sq_access;let a;
 if(token){try{a=(await upstream('/auth/v1/user',{token})).data;}catch(e){if(e.status!==401&&e.status!==403)throw e;}}
 if(!a&&c.sq_refresh){const s=(await upstream('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:c.sq_refresh}})).data;setSession(res,s);token=s.access_token;a=s.user;}
 if(a){const rows=await db('profiles',`?id=eq.${V.uuid(a.id)}&select=*&limit=1`,{token});if(rows?.[0]?.status==='active'){req.auth=a;req.user=rows[0];req.token=token;req.admin=await rpc('is_admin',{},token);}}
 next();}catch(e){if(e.status===401||e.status===403){clear(res);next();}else next(e);}}
function user(req,res,next){if(!req.user)return res.status(401).json({error:'auth_required'});next();}
function admin(req,res,next){if(!req.admin)return res.status(403).json({error:'admin_required'});next();}
async function limit(req,key,n=30,seconds=60){const allowed=await rpc('check_rate',{p_key:V.rateKey(`${key}:${req.user?.id||req.headers['x-real-ip']||req.socket.remoteAddress}`),p_limit:n,p_seconds:seconds},null,true);if(!allowed)fail(429,'try_later');}
app.use((req,res,next)=>{
 res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; media-src 'self' blob: https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"});
 if(process.env.NODE_ENV==='production')res.set('Strict-Transport-Security','max-age=31536000; includeSubDomains');
 if(req.path.startsWith('/api/')){res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){
 const origin=req.headers.origin;const host=req.headers.host;
 let valid=false;try{const u=new URL(origin);valid=u.host===host&&['https:','http:'].includes(u.protocol);}catch{}
 if(!valid||(req.headers['sec-fetch-site']&& !['same-origin','none'].includes(req.headers['sec-fetch-site'])))return res.status(403).json({error:'origin_required'});
 }}next();});
app.use('/api/media/upload',express.raw({type:()=>true,limit:'4mb'}));
app.use(express.json({limit:'256kb'}));
app.get('/health',(req,res)=>res.json({ok:true,configured:!!(SB&&KEY&&SECRET),architecture:'supabase-auth-rls'}));
app.use('/api',auth);
const profile=(p,a)=>({id:p.id,name:p.name,city:p.city,area:p.area,phone:p.phone||'',email:a?.email||'',avatarUrl:p.avatar_url,bio:p.bio,socialLinks:p.social_links,visibility:p.visibility||{},verified:p.verified,ts:Date.parse(p.created_at)});
async function sign(file){if(!file)return '';if(file.startsWith('https://'))return V.safeUrl(file);const r=await upstream('/storage/v1/object/sign/'+BUCKET+'/'+file,{method:'POST',secret:true,body:{expiresIn:3600}});return SB+'/storage/v1'+r.data.signedURL;}
async function present(l){const images=await Promise.all((l.images||[]).map(sign));const videos=await Promise.all((l.video_urls||[]).map(sign));return {...l,userId:l.user_id,desc:l.description,images,mediaPaths:l.images,videoPaths:l.video_urls,coverUrl:images[0]||'',galleryUrls:images.slice(1),videoUrls:videos,contactUrl:l.contact_url,moderationStatus:l.moderation_status,ts:Date.parse(l.created_at)};}
async function publicProfiles(ids,token){if(!ids.length)return [];return Promise.all((await rpc('public_profiles',{p_ids:[...new Set(ids)].slice(0,60)},token)).map(async p=>profile({...p,avatar_url:await sign(p.avatar_url)})));}
function feed(req){const b=req.query;const q=new URLSearchParams({select:'*',limit:'24',offset:String(Math.min(100000,Math.max(0,Number(b.offset)||0)))});q.set('moderation_status','eq.published');q.set('expires_at','gt.'+new Date().toISOString());for(const k of ['cat','subcategory','city','condition','type'])if(b[k]&&b[k]!=='all')q.set(k,'eq.'+V.text(b[k],80));if(b.min!==undefined&&b.min!=='')q.append('price','gte.'+Math.max(0,Number(b.min)||0));if(b.max!==undefined&&b.max!=='')q.append('price','lte.'+Math.max(0,Number(b.max)||0));if(b.featured==='true')q.set('featured','eq.true');if(b.q){const search=V.text(b.q,100).replace(/[^\p{L}\p{N}\s]/gu,'');if(search)q.set('or',`(title.ilike.*${search}*,description.ilike.*${search}*)`);}q.set('order',({old:'created_at.asc',price_low:'price.asc',cheap:'price.asc',price_high:'price.desc',expensive:'price.desc',views:'views.desc',featured:'featured.desc,created_at.desc'})[b.sort]||'pinned.desc,created_at.desc');return '?'+q;}
app.get(['/api/data','/api/listings'],async(req,res)=>{const ls=await db('listings',feed(req),{token:req.token});res.json({listings:await Promise.all(ls.map(present)),users:await publicProfiles(ls.map(l=>l.user_id),req.token),reviews:[],hasMore:ls.length===24});});
app.get('/api/profiles/:id',async(req,res)=>{const ps=await publicProfiles([V.uuid(req.params.id)],req.token);if(!ps[0])fail(404,'not_found');res.json({user:ps[0]});});
app.post('/api/register',async(req,res)=>{await limit(req,'register',5,3600);const b=req.body,identifier=V.text(b.identifier||b.email||b.phone,254),password=String(b.pass||''),email=identifier.includes('@')?identifier:'',phone=/^\+9647\d{9}$/.test(identifier)?identifier:'';if((!email&&!phone)||password.length<12)fail(400,'email_or_phone_and_strong_password_required');const body={password,data:{name:V.text(b.name),city:V.text(b.city,80)}};if(email)body.email=email;else body.phone=phone;const s=(await upstream('/auth/v1/signup',{method:'POST',body})).data;if(!s?.access_token||!s?.user)fail(409,'confirmation_must_be_disabled');setSession(res,s);const p=(await db('profiles',`?id=eq.${V.uuid(s.user.id)}&select=*&limit=1`,{token:s.access_token}))[0];if(!p||p.status!=='active')fail(403,'account_disabled');await rpc('record_login',{},s.access_token);res.status(201).json({user:profile(p,s.user),requiresVerification:false});});
async function login(req,res){await limit(req,'login',10,900);const s=(await upstream('/auth/v1/token?grant_type=password',{method:'POST',body:{email:V.text(req.body.email||req.body.phone,254),password:String(req.body.pass||'')}})).data;const token=s.access_token;const p=(await db('profiles',`?id=eq.${s.user.id}&select=*&limit=1`,{token}))[0];if(!p||p.status!=='active')fail(403,'account_disabled');if(req.path.includes('/admin/')){if(!await rpc('is_admin',{},token))fail(403,'admin_required');}setSession(res,s);await rpc('record_login',{},token);res.json({user:profile(p,s.user)});}
app.post(['/api/login','/api/admin/login'],login);
app.post(['/api/logout','/api/admin/logout'],async(req,res)=>{try{if(req.token)await upstream('/auth/v1/logout?scope=local',{method:'POST',token:req.token});}finally{clear(res);}res.json({ok:true});});
app.get('/api/me',user,async(req,res)=>{const p={...req.user,avatar_url:await sign(req.user.avatar_url)};res.json({user:profile(p,req.auth)});});
app.get('/api/admin/me',admin,(req,res)=>res.json({admin:{id:req.user.id}}));
async function ownedMedia(paths,req,video=false){if(!Array.isArray(paths))return [];const selected=paths.slice(0,video?2:8);for(const p of selected){if(video&&String(p).startsWith('https://')){const u=new URL(V.safeUrl(p));if(!['www.youtube.com','youtube.com','youtu.be','vimeo.com','www.vimeo.com'].includes(u.hostname))fail(400,'unsupported_video_url');continue;}if(!/^[0-9a-f-]{36}\/[0-9a-f-]{36}\.(jpg|png|webp|mp4|webm)$/.test(String(p)))fail(400,'uploaded_media_required');const m=(await db('media_objects','?path=eq.'+encodeURIComponent(p)+'&select=*&limit=1',{secret:true}))[0];if(!m||(!req.admin&&m.owner_id!==req.user.id)||!m.mime.startsWith(video?'video/':'image/'))fail(403,'media_not_owned');}return selected;}
app.patch('/api/me',user,async(req,res)=>{const b=req.body;const social={};for(const [k,v] of Object.entries(b.socialLinks||{}).slice(0,10))social[V.text(k,30)]=V.safeUrl(v);let avatar=req.user.avatar_url;if(b.avatarPath)avatar=(await ownedMedia([b.avatarPath],req))[0];const patch={name:V.text(b.name||req.user.name),city:V.text(b.city,80),area:V.text(b.area,80),bio:V.text(b.bio,1200),avatar_url:avatar,social_links:social,visibility:{showPhone:!!b.visibility?.showPhone,showSocial:b.visibility?.showSocial!==false}};if(!patch.name)fail(400,'name_required');const p=(await db('profiles',`?id=eq.${req.user.id}`,{method:'PATCH',body:patch,token:req.token,headers:{Prefer:'return=representation'}}))[0];p.avatar_url=await sign(p.avatar_url);res.json({user:profile(p,req.auth)});});
async function reauth(req){await limit(req,'reauth',5,900);const s=(await upstream('/auth/v1/token?grant_type=password',{method:'POST',body:{email:req.auth.email||undefined,phone:req.auth.phone||undefined,password:String(req.body.currentPassword||'')}})).data;await upstream('/auth/v1/logout?scope=local',{method:'POST',token:s.access_token});}
app.post('/api/me/password',user,async(req,res)=>{await reauth(req);if(String(req.body.newPassword||'').length<12)fail(400,'weak_password');await upstream('/auth/v1/user',{method:'PUT',token:req.token,body:{password:req.body.newPassword}});res.json({ok:true});});
app.post('/api/me/contact',user,async(req,res)=>{await reauth(req);const b={};if(req.body.newEmail)b.email=V.text(req.body.newEmail,254);if(req.body.newPhone){if(!/^\+9647\d{9}$/.test(req.body.newPhone))fail(400,'use_international_phone');b.phone=req.body.newPhone;}await upstream('/auth/v1/user',{method:'PUT',token:req.token,body:b});res.json({user:profile(req.user,req.auth),verificationRequired:true});});
app.post('/api/auth/phone-verify',user,async(req,res)=>{await limit(req,'otp',5,900);await upstream('/auth/v1/verify',{method:'POST',body:{phone:req.body.phone,token:req.body.code,type:'phone_change'}});await rpc('sync_auth_phone',{},req.token);res.json({ok:true});});
app.post('/api/auth/reset',async(req,res)=>{await limit(req,'reset',5,3600);await upstream('/auth/v1/recover',{method:'POST',body:{email:V.text(req.body.email,254)}});res.json({ok:true});});
app.post('/api/auth/verify',async(req,res)=>{await limit(req,'verify',10,900);if(!['signup','recovery','email_change'].includes(req.body.type))fail(400,'invalid_type');const s=(await upstream('/auth/v1/verify',{method:'POST',body:{token_hash:V.text(req.body.token_hash,256),type:req.body.type}})).data;setSession(res,s);if(req.body.type==='recovery'){const ticket=crypto.randomBytes(32).toString('hex');await rpc('issue_recovery',{p_hash:V.rateKey(ticket),p_user:s.user.id},null,true);cookie(res,'sq_recovery',ticket,600);}res.json({ok:true,recovery:req.body.type==='recovery'});});
app.post('/api/auth/recovery-password',user,async(req,res)=>{if(String(req.body.password||'').length<12)fail(400,'weak_password');const ticket=cookies(req).sq_recovery;if(!ticket||!await rpc('consume_recovery',{p_hash:V.rateKey(ticket),p_user:req.user.id},null,true))fail(403,'recovery_session_required');cookie(res,'sq_recovery','',0);await upstream('/auth/v1/user',{method:'PUT',token:req.token,body:{password:req.body.password}});await upstream('/auth/v1/logout?scope=global',{method:'POST',token:req.token});clear(res);res.json({ok:true});});
app.post('/api/me/logout-others',user,async(req,res)=>{await reauth(req);await upstream('/auth/v1/logout?scope=others',{method:'POST',token:req.token});res.json({ok:true});});
app.get('/api/me/settings',user,async(req,res)=>res.json({settings:(await db('user_settings',`?user_id=eq.${req.user.id}&select=*&limit=1`,{token:req.token}))[0]||{}}));
app.put('/api/me/settings',user,async(req,res)=>{if(JSON.stringify(req.body).length>8000)fail(400,'settings_too_large');await db('user_settings','',{method:'POST',token:req.token,headers:{Prefer:'resolution=merge-duplicates'},body:{user_id:req.user.id,preferences:req.body.preferences||{},notifications:req.body.notifications||{}}});res.json({ok:true});});
app.get('/api/listings/:id',async(req,res)=>{const l=(await db('listings',`?id=eq.${V.uuid(req.params.id)}&select=*&limit=1`,{token:req.token}))[0];if(!l)fail(404,'not_found');res.json({listing:await present(l),users:await publicProfiles([l.user_id],req.token)});});
app.get('/api/me/listings',user,async(req,res)=>{const ls=await db('listings',`?user_id=eq.${req.user.id}&order=created_at.desc&limit=24&offset=${Math.max(0,Number(req.query.offset)||0)}`,{token:req.token});res.json({listings:await Promise.all(ls.map(present))});});
app.post('/api/listings',user,async(req,res)=>{await limit(req,'listing',10,3600);const b=V.listing(req.body);b.user_id=req.user.id;b.images=await ownedMedia(req.body.mediaPaths||[],req);b.video_urls=await ownedMedia(req.body.videoPaths||req.body.videoUrls||[],req,true);const l=(await db('listings','',{method:'POST',body:b,token:req.token,headers:{Prefer:'return=representation'}}))[0];res.status(201).json({listing:await present(l)});});
app.put('/api/listings/:id',user,async(req,res)=>{const id=V.uuid(req.params.id),old=(await db('listings',`?id=eq.${id}&select=*&limit=1`,{token:req.token}))[0];if(!old||(!req.admin&&old.user_id!==req.user.id))fail(403,'forbidden');const b=V.listing(req.body);b.images=await ownedMedia(req.body.mediaPaths||old.images,req);b.video_urls=await ownedMedia(req.body.videoPaths||old.video_urls,req,true);const l=(await db('listings',`?id=eq.${id}`,{method:'PATCH',body:b,token:req.token,headers:{Prefer:'return=representation'}}))[0];if(!l)fail(403,'forbidden');res.json({listing:await present(l)});});
app.delete(['/api/listings/:id','/api/admin/listings/:id'],user,async(req,res)=>{const id=V.uuid(req.params.id);const ls=await db('listings',`?id=eq.${id}`,{method:'DELETE',token:req.token,headers:{Prefer:'return=representation'}});if(!ls?.length)fail(403,'forbidden');res.json({ok:true});});
app.post('/api/favorites',user,async(req,res)=>{const id=V.uuid(req.body.listingId);const q=`?user_id=eq.${req.user.id}&listing_id=eq.${id}`;const old=await db('favorites',q+'&limit=1',{token:req.token});await db('favorites',old.length?q:'',{method:old.length?'DELETE':'POST',token:req.token,body:old.length?undefined:{user_id:req.user.id,listing_id:id},headers:{Prefer:'resolution=ignore-duplicates'}});res.json({favs:await favs(req)});});
async function favs(req){return (await db('favorites',`?user_id=eq.${req.user.id}&order=created_at.desc&limit=100`,{token:req.token})).map(f=>({userId:f.user_id,listingId:f.listing_id,ts:Date.parse(f.created_at)}));}
const msg=m=>({...m,from:m.from_user_id,to:m.to_user_id,listingId:m.listing_id,ts:Date.parse(m.created_at)});
app.post('/api/messages',user,async(req,res)=>{await limit(req,'message',30,60);const b={from_user_id:req.user.id,to_user_id:V.uuid(req.body.to),listing_id:req.body.listingId?V.uuid(req.body.listingId):null,text:V.text(req.body.text,2000)};const m=(await db('messages','',{method:'POST',token:req.token,body:b,headers:{Prefer:'return=representation'}}))[0];res.status(201).json({message:msg(m)});});
app.post('/api/messages/read',user,async(req,res)=>{await db('messages',`?to_user_id=eq.${req.user.id}&from_user_id=eq.${V.uuid(req.body.from)}`,{method:'PATCH',body:{read:true},token:req.token});res.json({ok:true});});
app.post('/api/notifications/read',user,async(req,res)=>{await db('notifications',`?user_id=eq.${req.user.id}`,{method:'PATCH',body:{read:true},token:req.token});res.json({ok:true});});
app.get('/api/me/state',user,async(req,res)=>{const [fs,ms,ns]=await Promise.all([favs(req),db('messages','?order=created_at.desc&limit=100',{token:req.token}),db('notifications','?order=created_at.desc&limit=100',{token:req.token})]);res.json({favs:fs,messages:ms.map(msg).reverse(),notifications:ns.map(n=>({...n,userId:n.user_id,text:n.title,ts:Date.parse(n.created_at)})),reviews:[],users:await publicProfiles(ms.flatMap(m=>[m.from_user_id,m.to_user_id]),req.token)});});
app.post('/api/reports',user,async(req,res)=>{await limit(req,'report',5,3600);const b={user_id:req.user.id,listing_id:req.body.listingId?V.uuid(req.body.listingId):null,target_user_id:req.body.userId?V.uuid(req.body.userId):null,reason:V.text(req.body.reason||'other',80),note:V.text(req.body.note,500)};const r=(await db('reports','',{method:'POST',body:b,token:req.token,headers:{Prefer:'return=representation'}}))[0];res.status(201).json({report:r});});
app.get('/api/content',async(req,res)=>{const [cs,bs]=await Promise.all([db('site_content','?select=*&limit=50',{token:req.token}),db('banners','?order=position.asc&limit=10',{token:req.token})]);res.json({content:Object.fromEntries(cs.map(c=>[c.key,c])),banners:await Promise.all(bs.map(async b=>({...b,imageUrl:await sign(b.image_url),videoUrl:await sign(b.video_url),targetUrl:b.target_url,status:b.enabled?'published':'hidden'}))),socials:cs.find(c=>c.key==='socials')?.settings||{telegram:'https://t.me/HarryScloser6',youtube:''}});});
async function count(table,token,query=''){const r=await upstream(`/rest/v1/${table}?select=id${query}`,{method:'HEAD',token,headers:{Prefer:'count=exact',Range:'0-0'}});return Number((r.headers.get('content-range')||'*/0').split('/')[1])||0;}
app.get('/api/admin/data',admin,async(req,res)=>{const token=req.token,o=Math.max(0,Number(req.query.offset)||0);const [us,ls,rs,cs,bs,events]=await Promise.all([db('profiles',`?order=created_at.desc&limit=24&offset=${o}`,{token}),db('listings',`?order=created_at.desc&limit=24&offset=${o}`,{token}),db('reports','?order=created_at.desc&limit=24',{token}),db('site_content','?limit=50',{token}),db('banners','?limit=24&order=position.asc',{token}),db('audit_logs','?order=created_at.desc&limit=24',{token})]);res.json({users:us.map(p=>({...profile(p),status:p.status})),listings:await Promise.all(ls.map(present)),reports:rs,content:Object.fromEntries(cs.map(c=>[c.key,c])),banners:bs,ads:bs,events,stats:await rpc('admin_stats',{},token),hasMore:ls.length===24||us.length===24});});
app.get('/api/admin/audit',admin,async(req,res)=>res.json({events:await db('audit_logs',`?order=created_at.desc&limit=50&offset=${Math.max(0,Number(req.query.offset)||0)}`,{token:req.token})}));
app.patch('/api/admin/listings/:id',admin,async(req,res)=>{await rpc('admin_listing',{p_id:V.uuid(req.params.id),p_status:req.body.moderationStatus||null,p_featured:typeof req.body.featured==='boolean'?req.body.featured:null,p_pinned:typeof req.body.pinned==='boolean'?req.body.pinned:null},req.token);res.json({ok:true});});
app.patch('/api/admin/users/:id',admin,async(req,res)=>{await rpc('admin_profile',{p_id:V.uuid(req.params.id),p_status:V.text(req.body.status,20),p_verified:typeof req.body.verified==='boolean'?req.body.verified:null},req.token);res.json({ok:true});});
app.patch('/api/admin/reports/:id',admin,async(req,res)=>{await rpc('admin_report',{p_id:V.uuid(req.params.id),p_status:req.body.status,p_note:V.text(req.body.note,2000)},req.token);res.json({ok:true});});
app.patch('/api/admin/content/:key',admin,async(req,res)=>{const b={key:V.text(req.params.key,80),title:V.text(req.body.title,160),body:V.text(req.body.body,20000),kind:V.text(req.body.kind||'page',20),settings:req.body.settings||{}};await db('site_content','',{method:'POST',body:b,token:req.token,headers:{Prefer:'resolution=merge-duplicates'}});res.json({ok:true});});
app.post('/api/admin/banners',admin,async(req,res)=>{const image=(await ownedMedia(req.body.imagePath?[req.body.imagePath]:[],req))[0]||'',video=(await ownedMedia(req.body.videoPath?[req.body.videoPath]:[],req,true))[0]||'';if(!image&&!video)fail(400,'upload_required');const b={title:V.text(req.body.title,160),body:V.text(req.body.body,600),image_url:image,video_url:video,target_url:V.safeUrl(req.body.targetUrl),cta:V.text(req.body.cta||'اكتشف الآن',60),position:Math.floor(Number(req.body.position)||0),enabled:req.body.enabled!==false,starts_at:req.body.startsAt||new Date().toISOString(),ends_at:req.body.endsAt||null};await db('banners','',{method:'POST',body:b,token:req.token});res.status(201).json({ok:true});});
app.patch('/api/admin/banners/:id',admin,async(req,res)=>{const b={};for(const k of ['enabled','position','starts_at','ends_at'])if(k in req.body)b[k]=req.body[k];await db('banners','?id=eq.'+V.uuid(req.params.id),{method:'PATCH',body:b,token:req.token});res.json({ok:true});});
app.delete('/api/admin/banners/:id',admin,async(req,res)=>{await db('banners','?id=eq.'+V.uuid(req.params.id),{method:'DELETE',token:req.token});res.json({ok:true});});
app.post('/api/media/upload',user,async(req,res)=>{await limit(req,'upload',30,3600);const b=req.body;if(!Buffer.isBuffer(b))fail(400,'binary_required');const mime=V.mediaMime(b);if(!mime||mime!==req.headers['content-type'])fail(400,'invalid_file');const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm'})[mime],file=req.user.id+'/'+crypto.randomUUID()+'.'+ext;if(b.length>4*1024*1024)fail(413,'file_too_large');await upstream('/storage/v1/object/'+BUCKET+'/'+file,{method:'POST',secret:true,body:b,headers:{'Content-Type':mime,'x-upsert':'false'}});try{await db('media_objects','',{method:'POST',secret:true,body:{path:file,owner_id:req.user.id,mime,bytes:b.length}});}catch(e){await upstream('/storage/v1/object/'+BUCKET,{method:'DELETE',secret:true,body:{prefixes:[file]}});throw e;}await db('audit_logs','',{method:'POST',secret:true,body:{actor_id:req.user.id,action:'upload_media',target:file}});res.status(201).json({path:file,url:await sign(file)});});
app.delete('/api/media',user,async(req,res)=>{const file=String(req.body.path||'');const m=(await db('media_objects','?path=eq.'+encodeURIComponent(file)+'&limit=1',{secret:true}))[0];if(!m||(!req.admin&&m.owner_id!==req.user.id))fail(403,'forbidden');const [ls,bs,ps]=await Promise.all([db('listings','?or='+encodeURIComponent(`(images.cs.{${file}},video_urls.cs.{${file}})` )+'&select=id&limit=1',{secret:true}),db('banners','?or='+encodeURIComponent(`(image_url.eq.${file},video_url.eq.${file})`)+'&select=id&limit=1',{secret:true}),db('profiles','?avatar_url=eq.'+encodeURIComponent(file)+'&select=id&limit=1',{secret:true})]);if(ls.length||bs.length||ps.length)fail(409,'file_still_referenced');await upstream('/storage/v1/object/'+BUCKET,{method:'DELETE',secret:true,body:{prefixes:[file]}});await db('media_objects','?path=eq.'+encodeURIComponent(file),{method:'DELETE',secret:true});await db('audit_logs','',{method:'POST',secret:true,body:{actor_id:req.user.id,action:'delete_media',target:file}});res.json({ok:true});});
app.get('/api/me/export',user,async(req,res)=>{await limit(req,'export',2,3600);const token=req.token;res.json({profile:profile(req.user,req.auth),listings:await db('listings',`?user_id=eq.${req.user.id}&limit=100`,{token}),settings:await db('user_settings',`?user_id=eq.${req.user.id}`,{token}),note:'تصدير محدود لأول 100 إعلان؛ الرسائل وبيانات الآخرين غير مضمنة.'});});
app.delete('/api/admin/users/:id',admin,async(req,res)=>{await reauth(req);const id=V.uuid(req.params.id);if(id===req.user.id)fail(403,'cannot_delete_admin');await db('audit_logs','',{method:'POST',secret:true,body:{actor_id:req.user.id,action:'delete_user',target:id}});await upstream('/auth/v1/admin/users/'+id,{method:'DELETE',secret:true});res.json({ok:true});});
app.delete('/api/me',user,async(req,res)=>{await reauth(req);if(req.admin)fail(403,'cannot_delete_admin');await db('audit_logs','',{method:'POST',secret:true,body:{actor_id:req.user.id,action:'delete_account',target:req.user.id}});await upstream('/auth/v1/admin/users/'+req.user.id,{method:'DELETE',secret:true});clear(res);res.json({ok:true});});
app.post('/api/listings/:id/view',async(req,res)=>{await limit(req,'view:'+V.uuid(req.params.id),1,3600);await rpc('record_view',{p_id:req.params.id},null,true);res.json({ok:true});});
app.get('/api/reviews/:id',async(req,res)=>{const rows=await db('reviews','?target_id=eq.'+V.uuid(req.params.id)+'&order=created_at.desc&limit=24');res.json({reviews:rows.map(r=>({...r,authorId:r.author_id,targetId:r.target_id,ts:Date.parse(r.created_at)})),users:await publicProfiles(rows.map(r=>r.author_id),req.token)});});
app.post('/api/reviews',user,async(req,res)=>{await limit(req,'review',5,3600);const r=(await db('reviews','',{method:'POST',token:req.token,body:{author_id:req.user.id,target_id:V.uuid(req.body.targetId),rating:Number(req.body.rating),text:V.text(req.body.text,1000)},headers:{Prefer:'return=representation'}}))[0];res.status(201).json({review:{...r,authorId:r.author_id,targetId:r.target_id,ts:Date.parse(r.created_at)}});});
app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nDisallow: /api/\nDisallow: /auth/\nSitemap: ${ORIGIN}/sitemap.xml\n`));
app.get('/sitemap.xml',(req,res)=>{if(!ORIGIN)fail(503,'site_url_required');res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${ORIGIN.replace(/[&<>"']/g,'')}</loc></url></urlset>`);});
app.use('/assets',express.static(path.join(ROOT,'assets'),{maxAge:'1d',dotfiles:'deny'}));
for(const file of ['style.css','script.js','upgrade.js','register-sw.js','manifest.webmanifest','sw.js','icon-192.png','icon-512.png'])app.get('/'+file,(req,res)=>res.sendFile(path.join(ROOT,file)));
app.get('/auth/confirm',(req,res)=>res.sendFile(path.join(ROOT,'index.html')));
app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'not_found'});if(req.method==='GET'&&(req.path==='/'||req.path==='/index.html')){const fs=require('node:fs');let html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');if(ORIGIN&&/^https:\/\/[A-Za-z0-9.-]+$/.test(ORIGIN))html=html.replace('</head>',`<link rel="canonical" href="${ORIGIN}/"/><meta property="og:url" content="${ORIGIN}/"/></head>`);return res.type('html').send(html);}return res.status(404).end();});
app.use((err,req,res,next)=>{const status=err.status||err.statusCode||500;console.error('request_failed',status);res.status(status).json({error:status>=500?'service_unavailable':err.message});});
if(require.main===module)app.listen(Number(process.env.PORT||3000));
module.exports=app;
