'use strict';
// Progressive enhancement over the original design. No persistent browser data.
const uploads=new Map();let pendingVideos=[];let searchTimer;let requestSeq=0;let feedOffset=0;let feedLoading=false;
function mergeUsers(arr=[]){for(const u of arr)users=users.filter(x=>x.id!==u.id).concat(u);}
async function uploadMedia(file,progress){
 if(!currentUser)throw new Error('auth_required');
 if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type))throw new Error('نوع الملف غير مسموح');
 if(file.size>4*1024*1024)throw new Error('الحد الحالي 4 ميغابايت للملف، وفق مسار رفع Vercel');
 let body=file;
 if(file.type.startsWith('image/')){const data=await compressImage(file,1600,.82);body=await (await fetch(data)).blob();}
 return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/media/upload');xhr.setRequestHeader('Content-Type',body.type);xhr.withCredentials=true;xhr.upload.onprogress=e=>{if(e.lengthComputable&&progress)progress.value=Math.round(e.loaded/e.total*100);};xhr.onerror=()=>reject(new Error('upload_failed'));xhr.onload=()=>{let r;try{r=JSON.parse(xhr.responseText);}catch{r={};}if(xhr.status<200||xhr.status>=300)return reject(new Error(r.error||'upload_failed'));uploads.set(r.url,r.path);resolve(r);};xhr.send(body);});
}
function progressFor(form){let p=form.querySelector('progress');if(!p){p=document.createElement('progress');p.max=100;p.value=0;p.setAttribute('aria-label','تقدم الرفع');form.appendChild(p);}return p;}
function uploadControl(form,label,accept,onDone,multiple=false){const row=document.createElement('div');row.className='form-row';row.innerHTML=`<label>${esc(label)}</label><input class="inp" type="file" accept="${esc(accept)}" ${multiple?'multiple':''}/><div class="upload-preview"></div>`;form.appendChild(row);const input=row.querySelector('input');input.onchange=async()=>{input.disabled=true;const progress=progressFor(form);try{for(const file of [...input.files].slice(0,multiple?5:1)){const preview=document.createElement(file.type.startsWith('video/')?'video':'img');const u=URL.createObjectURL(file);preview.src=u;if(preview.tagName==='VIDEO')preview.controls=true;row.querySelector('.upload-preview').replaceChildren(preview);try{const r=await uploadMedia(file,progress);await onDone(r);}finally{URL.revokeObjectURL(u);}}toast('اكتمل الرفع','success');}catch(e){toast(e.message,'error');}finally{input.disabled=false;input.value='';}};return row;}
// Turn existing image compression hook into validated Storage upload.

const originalApi=api;
api=async function(url,opt={}){
 if(['/api/listings'].includes(url)&&opt.method==='POST'){
  const b=JSON.parse(opt.body);b.mediaPaths=(b.images||[]).map(x=>uploads.get(x)).filter(Boolean);b.videoPaths=pendingVideos.concat((b.videoUrls||[]).filter(x=>x.startsWith('https://'))).slice(0,2);const form=$('#formAdd');b.area=form?.elements.area?.value||'';b.subcategory=form?.elements.subcategory?.value||'';b.currency=form?.elements.currency?.value||'IQD';delete b.images;delete b.featured;opt={...opt,body:JSON.stringify(b)};
 }
 if(/^\/api\/listings\//.test(url)&&opt.method==='PUT'){
  const b=JSON.parse(opt.body);b.mediaPaths=b.mediaPaths||[];b.videoPaths=b.videoPaths||[];delete b.featured;opt={...opt,body:JSON.stringify(b)};
 }
 const r=await originalApi(url,opt);if(r.users)mergeUsers(r.users);if(r.requiresVerification)toast('راجع البريد لتأكيد الحساب');return r;
};
async function reloadFeed(append=false){
 if(feedLoading&&append)return;const seq=++requestSeq;feedLoading=true;const grid=$('#grid');grid?.setAttribute('aria-busy','true');
 const offset=append?feedOffset+24:0;const query=new URLSearchParams({...filters,offset:String(offset)});
 try{const data=await api('/api/listings?'+query);if(seq!==requestSeq)return;feedOffset=offset;listings=append?[...new Map(listings.concat(data.listings).map(l=>[l.id,l])).values()]:data.listings;mergeUsers(data.users);originalRenderListings();const more=$('#loadMoreListings');if(more)more.hidden=!data.hasMore;}
 catch(e){toast('تعذر تحميل الإعلانات: '+e.message,'error');}finally{if(seq===requestSeq){feedLoading=false;grid?.setAttribute('aria-busy','false');}}
}
const originalRenderListings=renderListings;let lastFilters='';
renderListings=function(){originalRenderListings();const f=JSON.stringify(filters);if(f!==lastFilters){lastFilters=f;clearTimeout(searchTimer);searchTimer=setTimeout(()=>reloadFeed(false),350);}};
const originalDetail=openDetail;
openDetail=async function(id){try{const r=await api('/api/listings/'+encodeURIComponent(id));listings=listings.filter(x=>x.id!==id).concat(r.listing);mergeUsers(r.users);originalDetail(id);}catch(e){toast('الإعلان غير متاح','error');}};
const originalProfile=openProfile;
openProfile=async function(id){try{const r=await api('/api/profiles/'+encodeURIComponent(id));mergeUsers([r.user]);const rs=await api('/api/reviews/'+encodeURIComponent(id));reviews=reviews.filter(x=>x.targetId!==id).concat(rs.reviews);mergeUsers(rs.users);originalProfile(id);const header=$('#profileBox .profile-header');if(header){const social=document.createElement('div');social.className='profile-social';for(const [name,url]of Object.entries(r.user.socialLinks||{})){if(!safeHttpUrl(url))continue;const a=document.createElement('a');a.href=url;a.rel='noopener noreferrer';a.target='_blank';a.textContent=name;social.appendChild(a);}if(r.user.phone){const phone=document.createElement('p');phone.textContent=r.user.phone;header.appendChild(phone);}header.appendChild(social);}}catch(e){toast('تعذر فتح الملف','error');}};
const originalMy=openMy;
openMy=async function(){if(!currentUser)return openAuth();try{const r=await api('/api/me/listings');listings=[...new Map(listings.concat(r.listings).map(x=>[x.id,x])).values()];originalMy();}catch(e){toast(e.message,'error');}};
const originalPrefs=applyPrefs;
applyPrefs=function(p){originalPrefs(p);if(currentUser)api('/api/me/settings',{method:'PUT',body:JSON.stringify({preferences:uiPrefs})}).catch(e=>toast('لم تُحفظ التفضيلات: '+e.message,'error'));};
const originalAdmin=renderAdminDashboard;
renderAdminDashboard=async function(){await originalAdmin();const box=$('#adminBox');if(!box||!$('#adminBannerForm'))return;
 try{const d=await api('/api/admin/data');const section=document.createElement('section');section.className='admin-section';section.innerHTML=`<h3>إدارة المستخدمين والبلاغات</h3><input class="inp" id="adminSearch" placeholder="بحث ضمن الصفحة الحالية"/>${d.users.map(u=>`<div class="admin-row" data-user-row="${esc(u.name)}"><b>${esc(u.name)}</b><span>${esc(u.status)}</span><button class="btn btn-ghost" data-profile-id="${u.id}">الملف</button><button class="btn" data-user-status="${u.id}" data-status="${u.status==='active'?'blocked':'active'}">${u.status==='active'?'تعطيل':'تفعيل'}</button></div>`).join('')}<h3>البلاغات</h3>${d.reports.map(r=>`<div class="admin-row"><div><b>${esc(r.reason)}</b><p>${esc(r.note)}</p><small>${esc(r.status)}</small></div><button class="btn" data-resolve="${r.id}">مراجعة</button></div>`).join('')}<h3>آخر النشاطات</h3>${d.events.map(e=>`<p>${esc(e.action)} — ${esc(e.target||'')} — ${esc(e.result)} — ${esc(new Date(e.created_at).toLocaleString('ar-IQ'))}</p>`).join('')}<p>نشطة: ${num(d.stats.active)} • مخفية: ${num(d.stats.hidden)} • مميزة: ${num(d.stats.featured)} • رسائل: ${num(d.stats.messages)}</p>`;box.appendChild(section);
 section.querySelector('#adminSearch').oninput=e=>section.querySelectorAll('[data-user-row]').forEach(x=>x.hidden=!x.dataset.userRow.includes(e.target.value));
 section.querySelectorAll('[data-profile-id]').forEach(b=>b.onclick=()=>openProfile(b.dataset.profileId));
 section.querySelectorAll('[data-user-status]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/users/'+b.dataset.userStatus,{method:'PATCH',body:JSON.stringify({status:b.dataset.status})});await renderAdminDashboard();}catch(e){toast(e.message,'error');}});
 section.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{const note=prompt('ملاحظة إدارية');if(note===null)return;try{await api('/api/admin/reports/'+b.dataset.resolve,{method:'PATCH',body:JSON.stringify({status:'resolved',note})});await renderAdminDashboard();}catch(e){toast(e.message,'error');}});
 const form=$('#adminBannerForm');form.elements.imageUrl.closest('.form-2').querySelector('[name=imageUrl]').disabled=true;let img='',vid='';uploadControl(form,'رفع صورة البنر','image/jpeg,image/png,image/webp',r=>{img=r.path;});uploadControl(form,'رفع فيديو قصير — 4MB','video/mp4,video/webm',r=>{vid=r.path;});
 const options=document.createElement('div');options.innerHTML='<label>زر الإعلان<input class="inp" name="cta" value="اكتشف الآن"/></label><label>الترتيب<input class="inp" name="position" type="number" value="0"/></label><label>البداية<input class="inp" name="startsAt" type="datetime-local"/></label><label>النهاية<input class="inp" name="endsAt" type="datetime-local"/></label>';form.appendChild(options);
 form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);try{await api('/api/admin/banners',{method:'POST',body:JSON.stringify({title:f.get('title'),body:f.get('body'),targetUrl:f.get('targetUrl'),cta:f.get('cta'),position:f.get('position'),imagePath:img,videoPath:vid,startsAt:f.get('startsAt')?new Date(f.get('startsAt')).toISOString():undefined,endsAt:f.get('endsAt')?new Date(f.get('endsAt')).toISOString():undefined})});toast('تمت إضافة البنر','success');await renderAdminDashboard();}catch(e){toast(e.message,'error');}};
 const socials=document.createElement('form');socials.innerHTML='<h3>روابط Footer</h3><label>Telegram<input class="inp" name="telegram" type="url"/></label><label>YouTube<input class="inp" name="youtube" type="url"/></label><button class="btn btn-primary">حفظ الروابط</button>';box.appendChild(socials);const links=(await api('/api/content')).socials;socials.elements.telegram.value=links.telegram||'';socials.elements.youtube.value=links.youtube||'';socials.onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/content/socials',{method:'PATCH',body:JSON.stringify({title:'التواصل الاجتماعي',body:'روابط التواصل الرسمية',kind:'settings',settings:{telegram:safeHttpUrl(socials.elements.telegram.value),youtube:safeHttpUrl(socials.elements.youtube.value)}})});toast('حُفظت الروابط','success');}catch(e){toast(e.message,'error');}};
 }catch(e){toast(e.message,'error');}
};
document.addEventListener('DOMContentLoaded',async()=>{
 const form=$('#formAdd');if(form){const fi=$('#fileInput'),zone=$('#uploader');async function add(files){for(const f of [...files].slice(0,5-pendingImages.length)){try{const r=await uploadMedia(f,progressFor(form));pendingImages.push(r.url);renderThumbs();}catch(e){toast(e.message,'error');}}}if(fi)fi.onchange=async e=>{await add(e.target.files);e.target.value='';};if(zone)zone.ondrop=async e=>{e.preventDefault();await add(e.dataTransfer.files);};$('#addUrlBtn')?.remove();$('#imgUrl')?.remove();uploadControl(form,'فيديو المنتج القصير — أقصى حجم 4MB','video/mp4,video/webm',r=>{if(pendingVideos.length<2)pendingVideos.push(r.path);});const feature=form.elements.featured;if(feature){feature.disabled=true;feature.closest('label').textContent='الترويج المجاني يُمنح تلقائياً لأول إعلان تنشره مرة واحدة فقط.';}const more=document.createElement('div');more.className='form-2';more.innerHTML='<label>المنطقة<input class="inp" name="area"/></label><label>القسم الفرعي<input class="inp" name="subcategory"/></label><label>العملة<select class="inp" name="currency"><option value="IQD">دينار عراقي</option><option value="USD">دولار أمريكي</option></select></label>';form.appendChild(more);}
 const pf=$('#formProfileSettings');if(pf){pf.elements.avatarUrl.readOnly=true;pf.elements.email.readOnly=true;let avatar='';uploadControl(pf,'رفع صورة الملف','image/jpeg,image/png,image/webp',r=>{avatar=r.path;pf.elements.avatarUrl.value=r.url;});pf.onsubmit=async e=>{e.preventDefault();const f=new FormData(pf);try{const socialLinks={};for(const k of ['telegram','social','youtube','instagram','facebook','tiktok','whatsapp','external'])if(f.get(k))socialLinks[k]=safeHttpUrl(f.get(k));const r=await api('/api/me',{method:'PATCH',body:JSON.stringify({name:f.get('name'),city:f.get('city'),bio:f.get('bio'),avatarPath:avatar||undefined,socialLinks,visibility:{showPhone:f.get('showPhone')==='on',showSocial:true}})});updateLocalUser(r.user);avatar='';toast('حُفظ الملف','success');}catch(e){toast(e.message,'error');}};for(const k of ['youtube','instagram','facebook','tiktok','whatsapp','external']){const div=document.createElement('div');div.className='form-row';div.innerHTML=`<label>${k}<input class="inp" name="${k}" type="url"/></label>`;pf.appendChild(div);}}
 const themes=$('#formPreferences .pref-options');if(themes)for(const theme of ['default','dark','ocean','sunset','luxury','minimal','glass'])themes.insertAdjacentHTML('beforeend',`<label><input type="radio" name="theme" value="${theme}"/><span>${theme}</span></label>`);
 const grid=$('#grid');if(grid){const more=document.createElement('button');more.id='loadMoreListings';more.className='btn btn-primary';more.textContent='تحميل المزيد';more.onclick=()=>reloadFeed(true);grid.after(more);}
 const reset=document.createElement('button');reset.type='button';reset.className='btn btn-ghost';reset.textContent='نسيت كلمة المرور';$('#formLogin')?.appendChild(reset);reset.onclick=async()=>{try{await api('/api/auth/reset',{method:'POST',body:JSON.stringify({email:$('#formLogin').elements.email.value})});toast('إذا كان البريد مسجلاً ستصلك رسالة استعادة');}catch(e){toast(e.message,'error');}};
 const params=new URLSearchParams(location.search);if(location.pathname==='/auth/confirm'&&params.get('token_hash')){try{const r=await api('/api/auth/verify',{method:'POST',body:JSON.stringify({token_hash:params.get('token_hash'),type:params.get('type')})});history.replaceState({},'','/');await hydrateFromServer();if(r.recovery){const password=prompt('كلمة مرور جديدة (12 حرفاً على الأقل)');if(password)await api('/api/auth/recovery-password',{method:'POST',body:JSON.stringify({password})});}toast('تم التحقق؛ سجّل الدخول عند الحاجة','success');}catch(e){toast('فشل التحقق: '+e.message,'error');}}
 try{const c=await api('/api/content');for(const [id,key]of [['footerTelegram','telegram'],['footerYoutube','youtube']]){const a=$('#'+id);if(a){const url=safeHttpUrl(c.socials[key]);if(url){a.href=url;a.target='_blank';a.rel='noopener noreferrer';}else a.hidden=true;}}}catch{}
 if(params.get('listing'))openDetail(params.get('listing'));
 setInterval(async()=>{if(!currentUser||document.hidden)return;try{const r=await api('/api/me/state');msgs=r.messages;favs=r.favs;notifs=r.notifications;mergeUsers(r.users);updateBadges();}catch{}},20000);
});
const baseEdit=openEditListing;
openEditListing=function(id){baseEdit(id);const form=$('#formEdit'),l=listings.find(x=>x.id===id);if(!form||!l)return;form.querySelector('[data-media-edit]')?.remove();let images=[...(l.mediaPaths||[])],videos=[...(l.videoPaths||[])];const group=document.createElement('section');group.dataset.mediaEdit='true';form.appendChild(group);function paint(){group.querySelector('.media-order')?.remove();const row=document.createElement('div');row.className='media-order';images.forEach((file,i)=>{const line=document.createElement('div');line.className='admin-row';line.innerHTML=`<span>${i===0?'الغلاف':'صورة '+(i+1)}</span><button class="btn" type="button" data-up>للأعلى</button><button class="btn btn-danger" type="button" data-del>إزالة</button>`;line.querySelector('[data-up]').onclick=()=>{if(i>0)[images[i-1],images[i]]=[images[i],images[i-1]];paint();};line.querySelector('[data-del]').onclick=()=>{images.splice(i,1);paint();};row.appendChild(line);});group.prepend(row);}paint();uploadControl(group,'إضافة صور','image/jpeg,image/png,image/webp',r=>{if(images.length<8)images.push(r.path);paint();},true);uploadControl(group,'إضافة فيديو قصير','video/mp4,video/webm',r=>{if(videos.length<2)videos.push(r.path);});const clearVideo=document.createElement('button');clearVideo.type='button';clearVideo.className='btn';clearVideo.textContent='إزالة كل الفيديوهات';clearVideo.onclick=()=>{videos=[];toast('ستزال الفيديوهات عند الحفظ');};group.appendChild(clearVideo);
 const contact=document.createElement('input');contact.className='inp';contact.type='url';contact.placeholder='رابط التواصل';contact.value=l.contactUrl||'';group.appendChild(contact);
 const condition=document.createElement('select');condition.className='inp';condition.innerHTML='<option value="new">جديد</option><option value="used">مستعمل</option><option value="refurbished">مجدد</option>';condition.value=l.condition;group.appendChild(condition);
 $('#editFeatured').disabled=true;
 const save=$('#saveEditBtn');save.onclick=async()=>{if(!form.reportValidity())return;save.disabled=true;try{const patch={...l,title:$('#editTitle').value,desc:$('#editDesc').value,price:$('#editPrice').value,cat:$('#editCat').value,city:$('#editCity').value,contactUrl:safeHttpUrl(contact.value),condition:condition.value,mediaPaths:images,videoPaths:videos};const r=await api('/api/listings/'+id,{method:'PUT',body:JSON.stringify(patch)});listings=listings.filter(x=>x.id!==id).concat(r.listing);closeOverlay('#ovEdit');renderAll();toast('حُفظت التعديلات','success');}catch(e){toast(e.message,'error');}finally{save.disabled=false;}};
};
document.addEventListener('DOMContentLoaded',()=>{
 const security=$('#formSecuritySettings');if(security){const note=document.createElement('p');note.className='hint';note.textContent='تغيير البريد يتطلب التأكيد. تغيير الهاتف يتطلب SMS provider ورمز التحقق. صيغة الهاتف: +9647xxxxxxxxx. لا توجد قائمة جلسات تفصيلية في هذه النسخة.';security.appendChild(note);const others=document.createElement('button');others.type='button';others.className='btn btn-ghost';others.textContent='تسجيل الخروج من الأجهزة الأخرى';others.onclick=async()=>{try{await api('/api/me/logout-others',{method:'POST',body:JSON.stringify({currentPassword:security.elements.currentPassword.value})});toast('أُلغيت رموز التجديد للأجهزة الأخرى؛ رموز الوصول تنتهي عند انتهاء صلاحيتها');}catch(e){toast(e.message,'error');}};security.appendChild(others);
 const otp=document.createElement('input');otp.className='inp';otp.placeholder='رمز تأكيد الهاتف';otp.inputMode='numeric';security.appendChild(otp);const verify=document.createElement('button');verify.type='button';verify.className='btn';verify.textContent='تأكيد تغيير الهاتف';verify.onclick=async()=>{try{await api('/api/auth/phone-verify',{method:'POST',body:JSON.stringify({phone:security.elements.newPhone.value,code:otp.value})});toast('تم تأكيد الهاتف');await hydrateFromServer();}catch(e){toast(e.message,'error');}};security.appendChild(verify);
 const del=document.createElement('button');del.type='button';del.className='btn btn-danger';del.textContent='حذف الحساب نهائياً';del.onclick=async()=>{if(!confirm('حذف الحساب والإعلانات نهائياً؟'))return;try{await api('/api/me',{method:'DELETE',body:JSON.stringify({currentPassword:security.elements.currentPassword.value})});currentUser=null;favs=[];msgs=[];notifs=[];closeOverlay('#ovAccount');await reloadFeed();renderAll();}catch(e){toast(e.message,'error');}};security.appendChild(del);}
 const footer=$('footer');if(footer){const nav=document.createElement('nav');nav.className='profile-social';for(const [key,label]of [['usage','سياسة الاستخدام'],['advertising','سياسة الإعلانات'],['content_policy','سياسة المحتوى'],['faq','الأسئلة الشائعة'],['blog','المدونة'],['jobs','الوظائف'],['help','المساعدة'],['support','مركز الدعم']]){const a=document.createElement('a');a.href='#';a.dataset.info=key;a.textContent=label;nav.appendChild(a);}footer.appendChild(nav);}
});
async function openInfo(type){try{const aliases={policy:'privacy',privacy_policy:'privacy',tos:'terms'};const r=await api('/api/content');const p=r.content[aliases[type]||type];if(!p){toast('الصفحة غير متاحة حالياً');return;}let overlay=$('#ovSitePage');if(!overlay){overlay=document.createElement('div');overlay.id='ovSitePage';overlay.className='overlay';overlay.innerHTML='<div class="modal lg"><div class="modal-head"><h2></h2><button class="close-x" data-close aria-label="إغلاق">×</button></div><div class="modal-body"></div></div>';document.body.appendChild(overlay);}overlay.querySelector('h2').textContent=p.title;const body=overlay.querySelector('.modal-body');body.textContent=p.body;body.style.whiteSpace='pre-line';openOverlay('#ovSitePage');}catch(e){toast('تعذر جلب الصفحة','error');}}
