package com.shorja.chat

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.shorja.chat.model.*
import com.shorja.chat.ui.ChatViewModel

class MainActivity : ComponentActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { MaterialTheme { MessagingApp() } } } }
@Composable fun MessagingApp(vm: ChatViewModel = viewModel()) { val s by vm.state.collectAsState(); var chat by remember { mutableStateOf<Conversation?>(null) }; if (!s.session) LoginScreen(s.loading, s.error, vm) else if (chat != null) ChatScreen(chat!!, s, vm) else HomeScreen(s, vm) }
@Composable private fun LoginScreen(loading: Boolean, error: String?, vm: ChatViewModel) { var register by remember { mutableStateOf(false) }; var email by remember { mutableStateOf("") }; var password by remember { mutableStateOf("") }; var username by remember { mutableStateOf("") }; var name by remember { mutableStateOf("") }; Column(Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.Center) { Text("مراسلة الشورجة", style = MaterialTheme.typography.headlineMedium); Spacer(Modifier.height(24.dp)); if (register) { OutlinedTextField(username, { username = it }, label = { Text("اسم المستخدم") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(name, { name = it }, label = { Text("الاسم") }, modifier = Modifier.fillMaxWidth()) }; OutlinedTextField(email, { email = it }, label = { Text("البريد الإلكتروني") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(password, { password = it }, label = { Text("كلمة المرور") }, modifier = Modifier.fillMaxWidth()); error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; Button(enabled = !loading, onClick = { if (register) vm.register(email, password, username, name) else vm.login(email, password) }, modifier = Modifier.fillMaxWidth().padding(top = 16.dp)) { Text(if (register) "إنشاء حساب" else "تسجيل الدخول") }; TextButton(onClick = { register = !register }) { Text(if (register) "لدي حساب بالفعل" else "حساب جديد") } } }
@Composable private fun HomeScreen(s: com.shorja.chat.ui.ChatState, vm: ChatViewModel) { var q by remember { mutableStateOf("") }; var selected by remember { mutableStateOf<Conversation?>(null) }; Column(Modifier.fillMaxSize().padding(16.dp)) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("المحادثات", style = MaterialTheme.typography.headlineSmall); TextButton(onClick = vm::logout) { Text("خروج") } }; OutlinedTextField(q, { q = it; vm.search(it) }, label = { Text("ابحث عن مستخدم") }, modifier = Modifier.fillMaxWidth()); s.error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; if (q.isNotBlank()) LazyColumn { items(s.profiles, key = { it.id }) { p -> ListItem(headlineContent = { Text(p.display_name ?: p.name ?: p.username ?: "مستخدم") }, supportingContent = { Text("@${p.username ?: ""}") }, modifier = Modifier.fillMaxWidth()) { vm.startChat(p) { selected = it } } } } else LazyColumn { items(s.conversations, key = { it.id }) { c -> ListItem(headlineContent = { Text(c.title ?: "محادثة") }, supportingContent = { Text(c.kind) }, modifier = Modifier.fillMaxWidth()) { selected = c } } }; selected?.let { ChatScreen(it, s, vm) } } }
@Composable private fun ChatScreen(c: Conversation, s: com.shorja.chat.ui.ChatState, vm: ChatViewModel) { var text by remember { mutableStateOf("") }; Column(Modifier.fillMaxSize().padding(16.dp)) { Text(c.title ?: "محادثة", style = MaterialTheme.typography.headlineSmall); LazyColumn(Modifier.weight(1f), reverseLayout = false) { items(s.messages, key = { it.id }) { m -> ListItem(headlineContent = { Text(if (m.deleted_at != null) "تم حذف هذه الرسالة" else m.content ?: "") }, supportingContent = { Text(if (m.is_edited) "تم التعديل" else m.created_at) }) } }; Row(Modifier.fillMaxWidth()) { OutlinedTextField(text, { text = it }, label = { Text("اكتب رسالة") }, modifier = Modifier.weight(1f)); Button(enabled = text.isNotBlank(), onClick = { vm.send(c, text); text = "" }) { Text("إرسال") } } } }
