'use strict';
const crypto = require('node:crypto');
function text(v,max=100){return String(v??'').trim().slice(0,max);}
function safeUrl(v){if(!v)return '';let u;try{u=new URL(String(v));}catch{throw Object.assign(new Error('invalid_url'),{status:400});}if(u.protocol!=='https:'||u.username||u.password||/^(localhost|127\.|0\.|169\.254\.|10\.|192\.168\.|\[|.*\.local$)/i.test(u.hostname))throw Object.assign(new Error('invalid_url'),{status:400});return u.href;}
function uuid(v){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v)))throw Object.assign(new Error('invalid_id'),{status:400});return v;}
function mediaMime(b){if(b.length<12)return '';if(b.subarray(0,3).equals(Buffer.from([255,216,255])))return 'image/jpeg';if(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return 'image/png';if(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')return 'image/webp';if(b.toString('ascii',4,8)==='ftyp')return 'video/mp4';if(b.subarray(0,4).equals(Buffer.from([26,69,223,163]))&&b.subarray(0,4096).includes(Buffer.from('webm')))return 'video/webm';return '';}
function listing(b){const price=Number(b.price??0);if(!Number.isFinite(price)||price<0||price>99999999999999)throw Object.assign(new Error('invalid_price'),{status:400});const r={title:text(b.title,180),description:text(b.desc??b.description,5000),cat:text(b.cat,60),subcategory:text(b.subcategory,60),city:text(b.city,80),area:text(b.area,80),price,currency:['IQD','USD'].includes(b.currency)?b.currency:'IQD',type:['sale','wanted','exchange'].includes(b.type)?b.type:'sale',condition:['new','used','refurbished'].includes(b.condition)?b.condition:'used',brand:text(b.brand,80),model:text(b.model,100),quantity:Math.max(1,Math.min(999999,Math.floor(Number(b.quantity)||1))),delivery:text(b.delivery||'pickup',30),negotiable:!!b.negotiable,tags:(Array.isArray(b.tags)?b.tags:[]).slice(0,10).map(x=>text(x,50)),contact_url:safeUrl(b.contactUrl??b.contact_url),moderation_status:b.moderationStatus==='draft'?'draft':'published'};if(r.title.length<3||r.description.length<3||!r.cat||!r.city)throw Object.assign(new Error('invalid_listing'),{status:400});return r;}
function rateKey(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
module.exports={text,safeUrl,uuid,mediaMime,listing,rateKey};
